# Generated by Django 4.2.7 on 2023-11-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booker',
            new_name='waiter',
        ),
    ]
