# Generated by Django 4.2.6 on 2023-11-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='BookingDate',
            new_name='inventory',
        ),
    ]
